services:
    fabstei_meteorit.menu_builder:
        class: Fabstei\MeteoritBundle\Menu\Builder
        arguments: [@knp_menu.factory, @security.context]

    fabstei_meteorit.menu.main: # Main Menu
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: fabstei_meteorit.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: mainMenu } # The alias is what is used to retrieve the menu

    fabstei_meteorit.menu.dropdown: # Dropdown Menu
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: fabstei_meteorit.menu_builder
        factory_method: createRightSideDropdownMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: dropdownMenu } # The alias is what is used to retrieve the menu