<?php

namespace Fabstei\MeteoritBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MeteoritRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeteoritRepository extends EntityRepository
{
}
